version: '3'
services:
  database:
    image: 'postgres:latest'
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: ${POSTGRES_DB} # The PostgreSQL default database (automatically created at first launch)
  backend:
    image: gramo37/prochesser-backend:latest
    ports: 
      - "5001:5001"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      BACKEND_URL: ${BACKEND_URL}
      INSTASEND_DEPOSIT_PERCENT: ${INSTASEND_DEPOSIT_PERCENT}
      CRYPTO_DEPOSIT_PERCENT: ${CRYPTO_DEPOSIT_PERCENT}
      CRYPTO_MERCHANT_ID: ${CRYPTO_MERCHANT_ID}
      CRYPTO_PAYMENT_API_KEY: ${CRYPTO_PAYMENT_API_KEY}
      CRYPTO_PAYOUT_API_KEY: ${CRYPTO_PAYOUT_API_KEY}
      CRYTPOMUS_URI: ${CRYTPOMUS_URI}
      BINANCE_SECRET_KEY: ${BINANCE_SECRET_KEY}
      BINANCE_API_KEY: ${BINANCE_API_KEY}
      SECRET_KEY: ${SECRET_KEY}
      NODE_ENV: ${NODE_ENV}
      BCRYPT_SECRET_KEY: ${BCRYPT_SECRET_KEY}
  frontend:
    image: gramo37/prochesser-frontend:latest
    ports:
      - "5173:5173"
    depends_on:
      - backend